### ISSUE TITLE
Add tests CI

### ISSUE THREAD

**Issue by Seb-sti1** [Seb-sti1/ProjectHub#11]
- [x] Add tests in CI
- [x] ~~Publish pre-release when merging on dev~~ _see #39_
- [x] ~~Publish release when merging on master~~ _see #39_
- [x] ~~Publish doc on GitLab Pages when merging to master~~ _see #40_

Links:
- https://github.com/marketplace/actions/gh-release
